In [5]:
import pandas as pd
import numpy as np

In [9]:
from sklearn.datasets import fetch_openml

boston = fetch_openml(name="boston", version=1, as_frame=True)

print(boston)
print(type(boston))

{'data':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

     PTRATIO       B  LSTAT
0       15.3  396.90   4.98
1       17.8  396.90   9.14
2       17.8  392.83   4.03
3       18.7  394.63   2.94
4       18.7  396.90   5.33
..       ...     ...    ...
501     21.0  391.99   9.67
502     21.0  396.90   9.08
503     21.0  396.90   5.64
504     21.0  393.45   6.48
505     21.0  396.90   7.88

[506 rows x 13 columns], 'target': 0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64, 'frame':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

     PTRATIO       B  LSTAT  MEDV
0       15.3  396.90   4.98  24.0
1       17.8  396.90   9.14  21.6
2       17.8  392.83   4.03  34.7
3       18.7  394.63   2.94  33.4
4       18.7  396.90   5.33  36.2
..       ...     ...    ...   ...
501     21.0  391.99   9.67  22.4
502     21.0  396.90   9.08  20.6
503     21.0  396.90   5.64  23.9
504     21.0  393.45   6.48  22.0
505     21.0  396.90   7.88  11.9

[506 rows x 14 columns], 'categories': None, 'feature_names': ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'], 'target_names': ['MEDV'], 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\nVariables in order:\nCRIM     per capita crime rate by town\nZN       proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS    proportion of non-retail business acres per town\nCHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\nNOX      nitric oxides concentration (parts per 10 million)\nRM       average number of rooms per dwelling\nAGE      proportion of owner-occupied units built prior to 1940\nDIS      weighted distances to five Boston employment centres\nRAD      index of accessibility to radial highways\nTAX      full-value property-tax rate per $10,000\nPTRATIO  pupil-teacher ratio by town\nB        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT    % lower status of the population\nMEDV     Median value of owner-occupied homes in $1000's\n\n\nInformation about the dataset\nCLASSTYPE: numeric\nCLASSINDEX: last\n\nDownloaded from openml.org.", 'details': {'id': '531', 'name': 'boston', 'version': '1', 'description_version': '1', 'format': 'ARFF', 'creator': ['D. and Rubinfeld', "D.L. 'Hedonic"], 'collection_date': '1978', 'upload_date': '2014-09-29T00:08:07', 'language': 'English', 'licence': 'Public', 'url': 'https://openml.org/data/v1/download/52643/boston.arff', 'parquet_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq', 'file_id': '52643', 'default_target_attribute': 'MEDV', 'tag': ['Data Science', 'Housing Economics', 'Kaggle', 'OpenML-Reg19', 'study_130', 'Urban Studies'], 'visibility': 'public', 'status': 'active', 'processing_date': '2020-11-20 20:16:37', 'md5_checksum': 'cdd361fb886627eaa80c92f90d0610cc'}, 'url': 'https://www.openml.org/d/531'}
<class 'sklearn.utils._bunch.Bunch'>

In [ ]:
# Create a pandas DataFrame 
boston_df = pd.DataFrame(boston.data, columns=boston.feature_names)
boston_df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88

In [13]:
# CSV file into pandas DataFrame
df = pd.read_csv("D:\\python code\\ALL_Libarary\\pandas\\advertising4D.csv")
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [14]:
df.head()
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

(200, 4)

In [25]:
#creating a DataFrame with random values
df_random = pd.DataFrame(np.random.rand(10, 5), columns=['A', 'B', 'C', 'D', 'E'])

In [26]:
df_random

          A         B         C         D         E
0  0.634921  0.861927  0.965343  0.433968  0.541087
1  0.187320  0.907191  0.129616  0.623652  0.066389
2  0.453170  0.990289  0.134288  0.163535  0.552470
3  0.080325  0.215977  0.479326  0.794703  0.114700
4  0.913318  0.579189  0.284866  0.135055  0.658734
5  0.302223  0.358180  0.693039  0.681869  0.348047
6  0.754174  0.537018  0.549800  0.756748  0.387082
7  0.946642  0.954660  0.943742  0.731328  0.701587
8  0.755254  0.709149  0.893856  0.578948  0.705002
9  0.033976  0.341717  0.132276  0.228785  0.850324

In [27]:
df.isnull().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [28]:
# Counting the values based on the label
df.value_counts('TV')

TV
17.2     2
76.4     2
199.8    2
197.6    2
184.9    2
        ..
289.7    1
290.7    1
292.9    1
293.6    1
296.4    1
Name: count, Length: 190, dtype: int64

In [29]:
df.groupby('TV').mean()

       radio  newspaper  sales
TV
0.7     39.6        8.7    1.6
4.1     11.6        5.7    3.2
5.4     29.9        9.4    5.3
7.3     28.1       41.4    5.5
7.8     38.9       50.6    6.6
...      ...        ...    ...
289.7   42.3       51.2   25.4
290.7    4.1        8.5   12.8
292.9   28.3       43.2   21.4
293.6   27.7        1.8   20.7
296.4   36.3      100.9   23.8

[190 rows x 3 columns]

In [30]:
df.count()

TV           200
radio        200
newspaper    200
sales        200
dtype: int64

In [31]:
df.mean()

TV           147.0425
radio         23.2640
newspaper     30.5540
sales         14.0225
dtype: float64

In [32]:
df.std()

TV           85.854236
radio        14.846809
newspaper    21.778621
sales         5.217457
dtype: float64

In [33]:
df.min()

TV           0.7
radio        0.0
newspaper    0.3
sales        1.6
dtype: float64

In [34]:
df.max()

TV           296.4
radio         49.6
newspaper    114.0
sales         27.0
dtype: float64

In [35]:
df.describe()

               TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [ ]:
# Adding a new column to DataFrame
df['price'] = df['TV']
df['price'] 
df

        TV  radio  newspaper  sales  price
0    230.1   37.8       69.2   22.1  230.1
1     44.5   39.3       45.1   10.4   44.5
2     17.2   45.9       69.3    9.3   17.2
3    151.5   41.3       58.5   18.5  151.5
4    180.8   10.8       58.4   12.9  180.8
..     ...    ...        ...    ...    ...
195   38.2    3.7       13.8    7.6   38.2
196   94.2    4.9        8.1    9.7   94.2
197  177.0    9.3        6.4   12.8  177.0
198  283.6   42.0       66.2   25.5  283.6
199  232.1    8.6        8.7   13.4  232.1

[200 rows x 5 columns]

In [38]:
# Removing a row
df.drop(index=0,axis=0)

        TV  radio  newspaper  sales  price
1     44.5   39.3       45.1   10.4   44.5
2     17.2   45.9       69.3    9.3   17.2
3    151.5   41.3       58.5   18.5  151.5
4    180.8   10.8       58.4   12.9  180.8
5      8.7   48.9       75.0    7.2    8.7
..     ...    ...        ...    ...    ...
195   38.2    3.7       13.8    7.6   38.2
196   94.2    4.9        8.1    9.7   94.2
197  177.0    9.3        6.4   12.8  177.0
198  283.6   42.0       66.2   25.5  283.6
199  232.1    8.6        8.7   13.4  232.1

[199 rows x 5 columns]

In [39]:
#Drop a column
df.drop(columns='price',axis =5)

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [40]:
df.iloc[2]

TV           17.2
radio        45.9
newspaper    69.3
sales         9.3
price        17.2
Name: 2, dtype: float64

In [42]:
#locating a particular column 
print(df.iloc[:,0])
print(df.iloc[:,1])

0      230.1
1       44.5
2       17.2
3      151.5
4      180.8
       ...
195     38.2
196     94.2
197    177.0
198    283.6
199    232.1
Name: TV, Length: 200, dtype: float64
0      37.8
1      39.3
2      45.9
3      41.3
4      10.8
       ...
195     3.7
196     4.9
197     9.3
198    42.0
199     8.6
Name: radio, Length: 200, dtype: float64

In [ ]:
df.corr()

                 TV     radio  newspaper     sales     price
TV         1.000000  0.054809   0.056648  0.782224  1.000000
radio      0.054809  1.000000   0.354104  0.576223  0.054809
newspaper  0.056648  0.354104   1.000000  0.228299  0.056648
sales      0.782224  0.576223   0.228299  1.000000  0.782224
price      1.000000  0.054809   0.056648  0.782224  1.000000

: